# Generated by Django 4.0.5 on 2022-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('my_rating', models.CharField(max_length=10)),
                ('Projects_done', models.CharField(max_length=5)),
                ('skill_desc', models.CharField(max_length=50)),
                ('image_link', models.CharField(max_length=300)),
            ],
        ),
    ]
