# Generated by Django 4.0.5 on 2022-07-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0002_skills_category_alter_skills_skill_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_desc',
            field=models.CharField(max_length=200),
        ),
    ]
