# Generated by Django 4.0.5 on 2022-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0003_alter_skills_skill_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=20)),
                ('project_duration', models.CharField(max_length=20)),
                ('git_web_link', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=40)),
                ('project_abstract', models.TextField()),
            ],
        ),
    ]
