# Generated by Django 4.0.5 on 2022-08-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
