# Generated by Django 4.0.5 on 2022-08-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0006_experience_experience_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_page.projects')),
            ],
        ),
    ]
