# Generated by Django 4.0.5 on 2022-08-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0007_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_skills',
            name='skill_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_page.skills'),
            preserve_default=False,
        ),
    ]
