# Generated by Django 4.0.5 on 2022-08-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0008_project_skills_skill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_page.experience')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_page.skills')),
            ],
        ),
    ]
