# Generated by Django 4.0.5 on 2022-09-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0009_experience_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_link', models.TextField()),
                ('certified_by', models.CharField(max_length=100)),
                ('Skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_page.skills')),
            ],
        ),
    ]
